name: rationale
channels:
  - pytorch
  - conda-forge
dependencies:
  - pytorch
  - cpuonly
  - numpy
  - networkx
  - ca-certificates
  - rdkit
  - certifi
  - flask
  - streamlit
  - argparse
  - streamlit_ketcher
  - chemprop
